---
# Variables for LVM configuration

# Volume group configuration
swygue_lvm_vg:
  name: ""
  physical_volumes: []
  size: ""

# Logical volume configuration  
swygue_lvm_lv:
  name: ""
  size: ""
  mount_point: ""
  filesystem: ""

# Filesystem options
swygue_lvm_fs:
  type: "ext4"
  options: []
  mount_options: "defaults"
